# Generated by Django 4.0.4 on 2022-05-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0003_slogan_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slogan',
            options={'verbose_name': 'Слоган', 'verbose_name_plural': 'Слоганы'},
        ),
        migrations.RenameField(
            model_name='slogan',
            old_name='type',
            new_name='slogan',
        ),
    ]
