# Generated by Django 4.0.4 on 2022-05-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0004_alter_slogan_options_rename_type_slogan_slogan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('-date_of_birth',), 'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='preview',
            field=models.ImageField(upload_to='photos/Electtions/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='region',
            field=models.CharField(max_length=150, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='slogan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOLOSOVANIE.slogan', verbose_name='Слоган'),
        ),
    ]
