# Generated by Django 4.0.4 on 2022-05-16 19:01

import GOLOSOVANIE.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0005_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('political_views', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='preview',
            field=models.ImageField(upload_to=GOLOSOVANIE.models.path_to_directory),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='slogan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='GOLOSOVANIE.slogan', verbose_name='Слоган'),
        ),
    ]
