# Generated by Django 4.0.4 on 2022-05-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0006_batch_alter_candidate_preview_alter_candidate_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='slogan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='GOLOSOVANIE.slogan', verbose_name='Слоган'),
        ),
    ]
