# Generated by Django 4.0.4 on 2022-05-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0007_alter_candidate_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GOLOSOVANIE.batch', verbose_name='Партия'),
        ),
    ]
