# Generated by Django 4.0 on 2022-05-22 18:01

import GOLOSOVANIE.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0013_candidate_support_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='preview',
            field=models.ImageField(upload_to=GOLOSOVANIE.services.path_to_directory, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='support_count',
            field=models.IntegerField(default=0, verbose_name='Поддерживают'),
        ),
    ]
