# Generated by Django 4.0 on 2022-05-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0015_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='login_img',
            field=models.ImageField(null=True, upload_to='photos/login_page/'),
        ),
    ]
