# Generated by Django 4.0 on 2022-05-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0016_startpage_login_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GOLOSOVANIE.myuser', verbose_name='Выдвиженец'),
        ),
    ]
