# Generated by Django 4.0 on 2022-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOLOSOVANIE', '0018_myuser_candidate_to_support_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='candidate_to_support',
        ),
        migrations.AddField(
            model_name='myuser',
            name='candidates',
            field=models.ManyToManyField(to='GOLOSOVANIE.Candidate', verbose_name='Кандидаты'),
        ),
    ]
